CREATE TABLE TBCATEGORIA(
	CODIGO VARCHAR(3) PRIMARY KEY,
	TITULO VARCHAR(30)
);

CREATE TABLE TPPRODUTO(
	SKU VARCHAR(3) PRIMARY KEY,
	NOME VARCHAR(30),
	CODCAT VARCHAR(3) REFERENCES TBCATEGORIA(CODIGO),
	QTDE INTEGER,
	PRECO NUMERIC(10,2)
);